FROM node:20-alpine
WORKDIR /app

# Copy dependency files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app
COPY . .

EXPOSE 3000
CMD ["node", "server.js"]
